// grounding-wiki.capsules.test.mjs — the capsule tier (docs/corpus-spec.md v2) against a
// throwaway git repo: CAPSULES.md generation (deterministic, headered, INDEX-ordered) and
// the adoption-keyed budget enforcement the freshness gate grew.
import { test } from "node:test";
import assert from "node:assert/strict";
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";
import { execFileSync } from "node:child_process";
import {
  renderCapsules, checkCapsuleTier, indexLineTarget, noteBody,
  CAPSULE_BUDGET, NOTE_BODY_BUDGET,
} from "../grounding-wiki/gates/capsules.mjs";
import { writeCapsules } from "../grounding-wiki/scripts/capsules.mjs";
import { validateFreshness, planFreshness } from "../grounding-wiki/gates/freshness.mjs";

const GIT_ID = ["-c", "user.email=test@test", "-c", "user.name=test"];
function git(cwd, ...args) {
  return execFileSync("git", [...GIT_ID, ...args], { cwd, encoding: "utf8" }).trim();
}

function note({ name, pin, description = "test note", body = "Body.", extraFm = "" }) {
  return `---\nname: ${name}\ndescription: ${description}\nkind: component\n${extraFm}sources:\n  - src/a.txt\nverified_against: ${pin}\n---\n\n# ${name}\n\n${body}\n`;
}

/** A repo whose INDEX deliberately orders notes non-alphabetically (beta before alpha). */
function makeRepo() {
  const repo = mkdtempSync(join(tmpdir(), "gw-capsules-"));
  git(repo, "init", "-q");
  mkdirSync(join(repo, "src"), { recursive: true });
  writeFileSync(join(repo, "src", "a.txt"), "one\n");
  git(repo, "add", ".");
  git(repo, "commit", "-qm", "c1");
  const pin = git(repo, "rev-parse", "HEAD");
  const wiki = join(repo, "docs", "wiki");
  mkdirSync(wiki, { recursive: true });
  writeFileSync(join(wiki, "INDEX.md"),
    "# index\n\nProse preamble that is not an entry.\n\n- [[beta]] — the beta note, listed first\n- [[alpha]] — the alpha note, listed second\n");
  writeFileSync(join(wiki, "beta.md"), note({ name: "beta", pin, description: "capsule for beta" }));
  writeFileSync(join(wiki, "alpha.md"), note({ name: "alpha", pin, description: "capsule for alpha" }));
  return { repo, wiki, pin };
}

/* ── R1: generation ─────────────────────────────────────────────────────── */

test("renderCapsules: header names generator + corpus commit; entries follow INDEX order", (t) => {
  const { repo, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));

  const out = renderCapsules(repo, "docs/wiki");
  assert.match(out, /Generated by grounding-wiki `scripts\/capsules\.mjs` at corpus commit [0-9a-f]{40}\./);
  assert.ok(out.includes(pin), "header pins the corpus commit (HEAD by default)");
  const beta = out.indexOf("- [[beta]] — the beta note, listed first\n  capsule for beta");
  const alpha = out.indexOf("- [[alpha]] — the alpha note, listed second\n  capsule for alpha");
  assert.ok(beta !== -1 && alpha !== -1, "each entry is the INDEX line followed by the capsule");
  assert.ok(beta < alpha, "entries keep INDEX.md order, not alphabetical order");
});

test("renderCapsules: deterministic and idempotent — same corpus state, byte-identical output", (t) => {
  const { repo } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const commit = git(repo, "rev-parse", "HEAD");
  assert.equal(renderCapsules(repo, "docs/wiki", { commit }), renderCapsules(repo, "docs/wiki", { commit }));

  const path = writeCapsules(repo, "docs/wiki", { commit });
  const first = readFileSync(path, "utf8");
  writeCapsules(repo, "docs/wiki", { commit });
  assert.equal(readFileSync(path, "utf8"), first, "regeneration is idempotent");
});

test("renderCapsules: unindexed notes are appended; reserved INDEX names are skipped", (t) => {
  const { repo, wiki, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  writeFileSync(join(wiki, "gamma.md"), note({ name: "gamma", pin, description: "capsule for gamma" }));
  writeFileSync(join(wiki, "INDEX.md"),
    "# index\n- [[beta]] — b\n- [[reserved-future-note]] — intentionally reserved\n- [alpha](alpha.md) — markdown-link style\n");

  const out = renderCapsules(repo, "docs/wiki", { commit: pin });
  assert.ok(!out.includes("reserved-future-note"), "INDEX-only reserved names get no entry");
  assert.ok(out.includes("- [alpha](alpha.md) — markdown-link style\n  capsule for alpha"), "markdown links resolve too");
  assert.ok(out.includes("- [[gamma]] (not in INDEX.md)\n  capsule for gamma"), "on-disk notes missing from INDEX still roll up");
});

test("renderCapsules: corpusDir-spelling-invariant — relative, trailing slash, absolute all byte-identical", (t) => {
  const { repo, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));

  const canonical = renderCapsules(repo, "docs/wiki", { commit: pin });
  for (const spelling of ["docs/wiki/", "./docs/wiki", join(repo, "docs", "wiki"), join(repo, "docs", "wiki") + "/"])
    assert.equal(renderCapsules(repo, spelling, { commit: pin }), canonical, `spelling: ${spelling}`);
  assert.ok(canonical.includes("<repo-root> docs/wiki\n"), "header embeds the normalized relative spelling");
});

test("CAPSULES.md generated with an absolute/trailing-slash corpusDir passes the default-spelling check", (t) => {
  const { repo } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  writeCapsules(repo, join(repo, "docs", "wiki") + "/", { commit: git(repo, "rev-parse", "HEAD") });

  const r = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r.fails, [], JSON.stringify(r.fails));
  assert.deepEqual(r.warns, [], JSON.stringify(r.warns));
});

test("pre-normalization header (old spelling, current content) degrades to a WARN with regeneration guidance", (t) => {
  const { repo } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const path = adopt(repo);

  // simulate a pre-fix file: the header command line embeds the invoking absolute spelling
  const preFix = readFileSync(path, "utf8")
    .replace("<repo-root> docs/wiki\n", `<repo-root> ${join(repo, "docs", "wiki")}/\n`);
  writeFileSync(path, preFix);

  const r = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r.fails, [], "current content behind an old header must not false-block");
  assert.ok(r.warns.some((w) => w.includes("pre-normalization corpusDir spelling") && w.includes("scripts/capsules.mjs")),
    JSON.stringify(r.warns));

  // a genuinely stale pre-fix file still fails as stale
  writeFileSync(join(repo, "docs", "wiki", "alpha.md"),
    note({ name: "alpha", pin: git(repo, "rev-parse", "HEAD"), description: "a NEW capsule for alpha" }));
  const r2 = validateFreshness(repo, "docs/wiki");
  assert.ok(r2.fails.some((f) => f.includes("CAPSULES.md: stale")), JSON.stringify(r2.fails));
});

test("indexLineTarget + noteBody primitives", () => {
  assert.equal(indexLineTarget("- [[overview]] — what it is"), "overview");
  assert.equal(indexLineTarget("- [alpha](alpha.md) — md link"), "alpha");
  assert.equal(indexLineTarget("## Heading with [[link]]"), null);
  assert.equal(indexLineTarget("- plain line, no ref"), null);
  assert.equal(noteBody("---\nname: x\n---\nBody line\n"), "Body line\n");
  assert.equal(noteBody("no frontmatter"), "no frontmatter");
});

/* ── R2: adoption-keyed enforcement in the freshness gate ───────────────── */

/** Generate CAPSULES.md so the corpus counts as adopted. */
function adopt(repo) {
  return writeCapsules(repo, "docs/wiki", { commit: git(repo, "rev-parse", "HEAD") });
}

test("adopted corpus with current CAPSULES.md passes; CAPSULES.md is never treated as a note", (t) => {
  const { repo } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  adopt(repo);
  const r = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r.fails, [], JSON.stringify(r.fails));
  assert.equal(r.checked, 2, "alpha + beta only — CAPSULES.md is not a checked note");
  assert.deepEqual(planFreshness(repo, "docs/wiki").problems, [], "plan ignores CAPSULES.md too");
});

test("adopted: over-budget capsule FAILs naming the note and the overage", (t) => {
  const { repo, wiki, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  writeFileSync(join(wiki, "alpha.md"),
    note({ name: "alpha", pin, description: "x".repeat(CAPSULE_BUDGET + 20) }));
  adopt(repo);
  const r = validateFreshness(repo, "docs/wiki");
  assert.ok(r.fails.some((f) => f.includes("alpha.md") && f.includes("20 over the 500-char capsule budget")),
    JSON.stringify(r.fails));
});

test("adopted: over-cap body FAILs pointing at the split rule; size_budget_exempt downgrades to WARN", (t) => {
  const { repo, wiki, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const fat = "y".repeat(NOTE_BODY_BUDGET + 100);
  writeFileSync(join(wiki, "alpha.md"), note({ name: "alpha", pin, body: fat }));
  adopt(repo);
  const r = validateFreshness(repo, "docs/wiki");
  assert.ok(r.fails.some((f) => f.includes("alpha.md") && f.includes("split summary-style")), JSON.stringify(r.fails));

  writeFileSync(join(wiki, "alpha.md"),
    note({ name: "alpha", pin, body: fat, extraFm: "size_budget_exempt: nothing splittable, single table\n" }));
  adopt(repo);
  const r2 = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r2.fails, [], JSON.stringify(r2.fails));
  assert.ok(r2.warns.some((w) => w.includes("alpha.md") && w.includes("size_budget_exempt: nothing splittable")),
    JSON.stringify(r2.warns));
});

test("adopted: stale or hand-edited CAPSULES.md FAILs naming the regeneration command", (t) => {
  const { repo, wiki, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const path = adopt(repo);

  // a description changes after generation → regenerate-and-compare mismatch
  writeFileSync(join(wiki, "alpha.md"), note({ name: "alpha", pin, description: "a NEW capsule for alpha" }));
  let r = validateFreshness(repo, "docs/wiki");
  assert.ok(r.fails.some((f) => f.includes("CAPSULES.md: stale") && f.includes("scripts/capsules.mjs")),
    JSON.stringify(r.fails));

  // regenerating is the named fix
  writeCapsules(repo, "docs/wiki", { commit: git(repo, "rev-parse", "HEAD") });
  assert.deepEqual(validateFreshness(repo, "docs/wiki").fails, []);

  // hand-editing the rollup is an error too
  writeFileSync(path, readFileSync(path, "utf8").replace("a NEW capsule for alpha", "hand-tuned capsule"));
  r = validateFreshness(repo, "docs/wiki");
  assert.ok(r.fails.some((f) => f.includes("CAPSULES.md: stale")), JSON.stringify(r.fails));

  // a headerless (foreign/hand-written) CAPSULES.md fails with the same fix
  writeFileSync(path, "just some hand-written rollup\n");
  r = validateFreshness(repo, "docs/wiki");
  assert.ok(r.fails.some((f) => f.includes("names no corpus commit") && f.includes("scripts/capsules.mjs")),
    JSON.stringify(r.fails));
});

test("unadopted corpus (no CAPSULES.md): the same checks are WARN-only — nothing blocks", (t) => {
  const { repo, wiki, pin } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  writeFileSync(join(wiki, "alpha.md"),
    note({ name: "alpha", pin, description: "x".repeat(CAPSULE_BUDGET + 1), body: "y".repeat(NOTE_BODY_BUDGET + 1) }));

  const r = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r.fails, [], JSON.stringify(r.fails));
  assert.ok(r.warns.some((w) => w.includes("warn-only until this corpus adopts CAPSULES.md") && w.includes("capsule budget")),
    JSON.stringify(r.warns));
  assert.ok(r.warns.some((w) => w.includes("warn-only until this corpus adopts CAPSULES.md") && w.includes("note budget")),
    JSON.stringify(r.warns));
});

test("existing freshness behavior is unchanged by the capsule tier: within-budget v1 corpus stays green", (t) => {
  const { repo } = makeRepo();
  t.after(() => rmSync(repo, { recursive: true, force: true }));
  const r = validateFreshness(repo, "docs/wiki");
  assert.deepEqual(r.fails, [], JSON.stringify(r.fails));
  assert.deepEqual(r.warns, [], "no v2 notices for a within-budget unadopted corpus");
  assert.equal(r.checked, 2);
});
