#!/usr/bin/env node
// tiers.mjs — generate the implementer agent definitions from `.claude/model-tiers.json`
// (dual-use: library + CLI). Sibling of plant.mjs, same report vocabulary and consent rules.
//
// WHY A GENERATOR AND NOT JUST A CONFIG FILE. A config file cannot make dispatch obey it.
// This harness honors exactly ONE model pin: `model:` in an agent definition's frontmatter
// (`.claude/agents/<name>.md`). The dispatch call's `model` parameter was observed on
// 2026-07-31 being silently ignored — dispatches meant for one model ran on the
// orchestrator's session model at ~2x the unit price before being killed
// (docs/design/board-cost-test-runbook.md, TASK-74 row). So the chain is:
//
//     .claude/model-tiers.json  →  tiers.mjs  →  .claude/agents/*.md  →  harness
//
// The config is the SOURCE (hand-edited, tracked, outside every marker — bumping a model ID
// is a one-line edit, never a bootstrap re-plant + drift + --force). The generated agent def
// is the PIN (what actually runs). Anything that skips the generator is a table that
// recommends, not a pin that holds.
//
// The tier map is deliberately OPEN: model families rev on independent cadences and new ones
// arrive unannounced, so nothing here enumerates a closed list of tier names. Adding `fable`
// (or a family that does not exist yet) is a config key, not a code change.
//
//   node tiers.mjs --root <dir> [--check] [--force]
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { render } from "../lib/template.mjs";
import { runAsCli } from "../lib/cli.mjs";

const here = dirname(fileURLToPath(import.meta.url));
export const CONFIG_PATH = join(".claude", "model-tiers.json");
export const AGENTS_DIR = join(".claude", "agents");
/** The marker line that identifies a file this generator owns. */
export const GENERATED_MARKER = "<!-- GENERATED by pdlc/scripts/tiers.mjs";

/** Where a tier's generated agent definition lives, relative to the project root. */
export function agentPath(tier) {
  return join(AGENTS_DIR, `${tier}-implementer.md`);
}

/**
 * Validate a parsed model-tiers config. Throws a NAMED error on every rejection — an unknown
 * `defaultTier` must never degrade into a silent skip that later resolves to the session
 * model, which is the exact failure this whole mechanism exists to prevent.
 * Returns the config unchanged so callers can validate-and-assign in one expression.
 */
export function validateConfig(config) {
  if (!config || typeof config !== "object" || Array.isArray(config)) {
    throw new Error(`${CONFIG_PATH}: expected a JSON object`);
  }
  const { tiers, defaultTier, escalationTier } = config;
  if (!tiers || typeof tiers !== "object" || Array.isArray(tiers)) {
    throw new Error(`${CONFIG_PATH}: "tiers" must be an object mapping tier name → tier config`);
  }
  const names = Object.keys(tiers);
  if (names.length === 0) throw new Error(`${CONFIG_PATH}: "tiers" is empty — declare at least one tier`);

  for (const name of names) {
    if (!/^[a-z0-9][a-z0-9-]*$/.test(name)) {
      throw new Error(`${CONFIG_PATH}: tier name "${name}" must be lowercase alphanumeric with dashes (it becomes a filename and an agent name)`);
    }
    const tier = tiers[name];
    if (!tier || typeof tier !== "object" || Array.isArray(tier)) {
      throw new Error(`${CONFIG_PATH}: tier "${name}" must be an object`);
    }
    if (typeof tier.model !== "string" || tier.model.trim() === "") {
      throw new Error(`${CONFIG_PATH}: tier "${name}" is missing a "model" string — a tier with no model ID resolves to the session model at dispatch`);
    }
    if (typeof tier.for !== "string" || tier.for.trim() === "") {
      throw new Error(`${CONFIG_PATH}: tier "${name}" is missing a "for" string — the dispatched agent reads it to know its own scope`);
    }
    if (tier.fallback !== undefined && (typeof tier.fallback !== "string" || tier.fallback.trim() === "")) {
      throw new Error(`${CONFIG_PATH}: tier "${name}" has a non-string "fallback"`);
    }
  }
  // Pointer fields must name real tiers. Both are required: a config with no declared default
  // leaves "which tier does an unmarked task get?" to whoever reads it next.
  for (const [field, value] of [["defaultTier", defaultTier], ["escalationTier", escalationTier]]) {
    if (value === undefined) {
      if (field === "escalationTier") continue; // optional: a host may run with no escalation path
      throw new Error(`${CONFIG_PATH}: missing "defaultTier" — name the tier an unmarked task dispatches to`);
    }
    if (!names.includes(value)) {
      throw new Error(`${CONFIG_PATH}: "${field}" names "${value}", which is not a declared tier (declared: ${names.join(", ")})`);
    }
  }
  return config;
}

/** Read + validate the config at `<root>/.claude/model-tiers.json`. */
export function readConfig(root) {
  const p = join(resolve(root), CONFIG_PATH);
  if (!existsSync(p)) throw new Error(`${CONFIG_PATH}: not found in ${root} — run pdlc:bootstrap to plant it`);
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(p, "utf8"));
  } catch (err) {
    throw new Error(`${CONFIG_PATH}: invalid JSON — ${err.message}`);
  }
  return validateConfig(parsed);
}

/**
 * The one-line `description:` a tier's agent definition carries. It is what a dispatching
 * orchestrator reads when choosing an agent, so it names the model and the scope, and marks
 * an escalation tier as operator-gated.
 */
export function tierDescription(name, tier) {
  const parts = [`Sweep implementer pinned to ${tier.model}`];
  if (tier.escalation) parts.push("ESCALATION TIER — dispatch requires a recorded operator checkpoint");
  parts.push(`For: ${tier.for}`);
  if (tier.fallback) parts.push(`Fallback when ${tier.model} is unavailable in the subscription: ${tier.fallback} (record which model actually served).`);
  return parts.join(". ").replace(/\.\./g, ".");
}

/** Render one tier's agent definition from the template. */
export function renderAgent(templateText, name, tier) {
  const cautionLines = [];
  if (tier.contextWindow) cautionLines.push(`**Context window:** ${tier.contextWindow}.`);
  if (tier.caution) cautionLines.push(`**Caution:** ${tier.caution}`);
  if (tier.fallback) cautionLines.push(`**Fallback:** if \`${tier.model}\` is unavailable, this tier degrades to \`${tier.fallback}\` — the orchestrator records which model actually served.`);
  if (tier.escalation) cautionLines.push("**This is an escalation tier.** Reaching it is an operator checkpoint that must already have been recorded before this dispatch was made.");
  const caution = cautionLines.length ? "\n" + cautionLines.join("\n") + "\n" : "";

  return render(templateText, {
    TIER: name,
    MODEL: tier.model,
    DESCRIPTION: tierDescription(name, tier),
    FOR: tier.for,
    CAUTION_BLOCK: caution,
  }).replace(/\n{3,}/g, "\n\n");
}

/**
 * Is this on-disk agent definition one WE generated? Only generated files are eligible for
 * silent replacement; a hand-authored def at the same path is the operator's, and is reported
 * as `drifted` rather than clobbered — same consent semantics plant.mjs gives CLAUDE.md.
 */
function isGenerated(text) {
  return text.includes(GENERATED_MARKER);
}

/**
 * Generate (or report on, with check:true) the implementer agent definitions in `root`.
 *
 * Returns { config, defaultTier, escalationTier, agents, missing } where `agents` maps a
 * tier name → { path, model, status } and status is one of:
 *   created   — no file at that path yet
 *   unchanged — on disk already equals what this config renders
 *   replaced  — regenerated (a generated file whose content was stale, or any file with --force)
 *   drifted   — a file we did NOT generate, or a generated one edited by hand; needs --force
 */
export function generate(root, { check = false, force = false, templatePath, config } = {}) {
  root = resolve(root);
  templatePath ??= join(here, "..", "templates", "implementer-agent.md");
  config ??= readConfig(root);
  validateConfig(config);

  const templateText = readFileSync(templatePath, "utf8");
  const agents = {};

  for (const [name, tier] of Object.entries(config.tiers)) {
    const rel = agentPath(name);
    const abs = join(root, rel);
    const expected = renderAgent(templateText, name, tier);

    // Three cases: absent → created; identical → unchanged; different → ours to refresh
    // (`replaced`) only if we generated it, else it is the operator's file and needs --force.
    let status;
    if (!existsSync(abs)) status = "created";
    else {
      const current = readFileSync(abs, "utf8");
      if (current === expected) status = "unchanged";
      else if (isGenerated(current) || force) status = "replaced";
      else status = "drifted";
    }

    if (!check && (status === "created" || status === "replaced")) {
      mkdirSync(dirname(abs), { recursive: true });
      writeFileSync(abs, expected);
    }
    agents[name] = { path: rel, model: tier.model, status };
  }

  const missing = check ? [] : Object.values(agents).filter((a) => !existsSync(join(root, a.path))).map((a) => a.path);
  return {
    config: CONFIG_PATH,
    defaultTier: config.defaultTier,
    escalationTier: config.escalationTier ?? null,
    agents,
    missing,
  };
}

if (runAsCli(import.meta.url)) {
  const args = process.argv.slice(2);
  const opt = (name) => { const i = args.indexOf(name); return i === -1 ? undefined : args[i + 1]; };
  const root = opt("--root");
  if (!root) {
    console.error("usage: tiers.mjs --root <dir> [--check] [--force]");
    process.exit(2);
  }
  const check = args.includes("--check");
  let report;
  try {
    report = generate(root, { check, force: args.includes("--force") });
  } catch (err) {
    console.error(`tiers: ${err.message}`);
    process.exit(2);
  }
  for (const [name, a] of Object.entries(report.agents)) {
    if (a.status === "drifted") {
      console.error(`tiers: ${a.path} was not generated by this script (or was hand-edited) — showing as drifted; re-run with --force to replace it, or move your edits into ${CONFIG_PATH}`);
    }
  }
  console.log(JSON.stringify(report, null, 2));
  const pending = Object.values(report.agents).some((a) => a.status !== "unchanged");
  const drifted = Object.values(report.agents).some((a) => a.status === "drifted");
  if (check && pending) process.exit(1); // --check: nonzero when generating would change something
  // A drift in WRITE mode means that tier's pin is not what the config says and this run did
  // not fix it. Exiting 0 there would report success over a live config/pin mismatch — the
  // precise silent state this whole mechanism exists to prevent.
  if (drifted) process.exit(1);
  if (report.missing.length) process.exit(1);
}
